import Head from "next/head"
import React, { Fragment, useState } from "react"
import { Listbox, Transition } from '@headlessui/react'
import { CheckIcon, SelectorIcon } from '@heroicons/react/solid'

const headingFont = [
  { name: 'Aclonica' },
  { name: 'Archivo' },
  { name: 'El Messiri' },
  { name: 'Kantumruy Pro' },
  { name: 'Lato' },
  { name: 'Manjari' },
  { name: 'Marmelad' },
  { name: 'Nunito' },
  { name: 'Outfit' },
  { name: 'Puritan' },
  { name: 'Quattrocento Sans' },
  { name: 'Quicksand' },
  { name: 'Readex Pro' },
  { name: 'Syne' },
  { name: 'Work Sans' },
]

const bodyFont = [
  { name: 'Nunito' },
  { name: 'Archivo' },
  { name: 'El Messiri' },
  { name: 'Kantumruy Pro' },
  { name: 'Lato' },
  { name: 'Manjari' },
  { name: 'Marmelad' },
  { name: 'Aclonica' },
  { name: 'Outfit' },
  { name: 'Puritan' },
  { name: 'Quattrocento Sans' },
  { name: 'Quicksand' },
  { name: 'Readex Pro' },
  { name: 'Syne' },
  { name: 'Work Sans' },
]

const colour = ['#43AA8B']

export default function Home() {
  const [selectedHeading, setSelectedHeading] = useState(headingFont[0])
  const [selectedBody, setSelectedBody] = useState(bodyFont[0])
  return (
    <div>
      <Head>
        <title>Fontester | The ultimate font-pair testing website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Aclonica&family=Archivo:ital,wght@0,100;0,300;0,500;0,700;0,900;1,100;1,500;1,700;1,900&family=El+Messiri:wght@400;700&family=Kantumruy+Pro:ital,wght@0,100;0,300;0,500;0,600;0,700;1,100;1,300;1,400;1,600;1,700&family=Lato:wght@300;400;700&family=Manjari:wght@100;400;700&family=Marmelad&family=Nunito:ital,wght@0,300;0,400;0,500;0,700;0,900;1,300;1,400;1,500;1,700;1,900&family=Outfit:wght@300;400;500;700&family=Puritan:wght@400;700&family=Quattrocento+Sans:ital,wght@0,400;0,700;1,400;1,700&family=Quicksand:wght@400;500;600;700&family=Readex+Pro:wght@300;500;700&family=Syne:wght@400;500;700;800&family=Work+Sans:wght@300;400;500;700;800&display=swap" rel="stylesheet" />
      </Head>

      <main className="bg-white w-screen min-h-screen flex flex-col">
        {/* Font dropdowns section */}
        <div className="px-8 py-4 flex flex-col sm:flex-row space-x-0 sm:space-x-4 space-y-4 sm:space-y-0 border-b border-gray-400">
          {/* Heading font dropdown */}
          <div className="flex flex-col space-y-1">
            <p className="text-sm text-gray-600">Heading font</p>
            <div className="w-72 z-50">
              <Listbox value={selectedHeading} onChange={setSelectedHeading}>
                <div className="relative mt-1">
                  <Listbox.Button className="relative w-full cursor-default rounded-lg bg-white py-2 pl-3 pr-10 text-left border border-gray-400 focus:outline-none focus-visible:border-indigo-500 focus-visible:ring-2 focus-visible:ring-white focus-visible:ring-opacity-75 focus-visible:ring-offset-2 focus-visible:ring-offset-orange-300 sm:text-sm">
                    <span className="block truncate" style={{ fontFamily: `${selectedHeading.name}` }}>{selectedHeading.name}</span>
                    <span className="pointer-events-none absolute inset-y-0 right-0 flex items-center pr-2">
                      <SelectorIcon
                        className="h-5 w-5 text-gray-400"
                        aria-hidden="true"
                      />
                    </span>
                  </Listbox.Button>
                  <Transition
                    as={Fragment}
                    leave="transition ease-in duration-100"
                    leaveFrom="opacity-100"
                    leaveTo="opacity-0"
                  >
                    <Listbox.Options className="absolute mt-1 max-h-60 w-full overflow-auto rounded-md bg-white py-1 text-base shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none sm:text-sm">
                      {headingFont.map((person, personIdx) => (
                        <Listbox.Option
                          key={personIdx}
                          className={({ active }) =>
                            `relative cursor-default select-none py-2 pl-10 pr-4 ${active ? 'bg-amber-100 text-amber-900' : 'text-gray-900'
                            }`
                          }
                          value={person}
                        >
                          {({ selectedHeading }) => (
                            <>
                              <span
                                className={`block truncate ${selectedHeading ? 'font-medium' : 'font-normal'
                                  }`}
                                style={{ fontFamily: `${person.name}` }}
                              >
                                {person.name}
                              </span>
                              {selectedHeading ? (
                                <span className="absolute inset-y-0 left-0 flex items-center pl-3 text-amber-600">
                                  <CheckIcon className="h-5 w-5" aria-hidden="true" />
                                </span>
                              ) : null}
                            </>
                          )}
                        </Listbox.Option>
                      ))}
                    </Listbox.Options>
                  </Transition>
                </div>
              </Listbox>
            </div>
          </div>

          {/* Body font dropdown */}
          <div className="flex flex-col space-y-1">
            <p className="text-sm text-gray-600">Body font</p>
            <div className="w-72 z-40">
              <Listbox value={selectedBody} onChange={setSelectedBody}>
                <div className="relative mt-1">
                  <Listbox.Button className="relative w-full cursor-default rounded-lg bg-white py-2 pl-3 pr-10 text-left border border-gray-400 focus:outline-none focus-visible:border-indigo-500 focus-visible:ring-2 focus-visible:ring-white focus-visible:ring-opacity-75 focus-visible:ring-offset-2 focus-visible:ring-offset-orange-300 sm:text-sm">
                    <span className="block truncate" style={{ fontFamily: `${selectedBody.name}` }}>{selectedBody.name}</span>
                    <span className="pointer-events-none absolute inset-y-0 right-0 flex items-center pr-2">
                      <SelectorIcon
                        className="h-5 w-5 text-gray-400"
                        aria-hidden="true"
                      />
                    </span>
                  </Listbox.Button>
                  <Transition
                    as={Fragment}
                    leave="transition ease-in duration-100"
                    leaveFrom="opacity-100"
                    leaveTo="opacity-0"
                  >
                    <Listbox.Options className="absolute mt-1 max-h-60 w-full overflow-auto rounded-md bg-white py-1 text-base shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none sm:text-sm">
                      {bodyFont.map((person, personIdx) => (
                        <Listbox.Option
                          key={personIdx}
                          className={({ active }) =>
                            `relative cursor-default select-none py-2 pl-10 pr-4 ${active ? 'bg-amber-100 text-amber-900' : 'text-gray-900'
                            }`
                          }
                          value={person}
                        >
                          {({ selectedBody }) => (
                            <>
                              <span
                                className={`block truncate ${selectedBody ? 'font-medium' : 'font-normal'
                                  }`}
                                style={{ fontFamily: `${person.name}` }}
                              >
                                {person.name}
                              </span>
                              {selectedBody ? (
                                <span className="absolute inset-y-0 left-0 flex items-center pl-3 text-amber-600">
                                  <CheckIcon className="h-5 w-5" aria-hidden="true" />
                                </span>
                              ) : null}
                            </>
                          )}
                        </Listbox.Option>
                      ))}
                    </Listbox.Options>
                  </Transition>
                </div>
              </Listbox>
            </div>
          </div>
        </div>

        {/* Hero section */}
        <div className="p-8 flex flex-col sm:flex-row space-y-4 sm:space-y-0 justify-between">
          <div className="w-full sm:w-1/2">
            <img
              className="w-full h-auto sm:h-3/4 object-cover"
              src="/image 1.jpg"
            />
          </div>
          <div className="w-full h-full sm:w-1/2 pl-0 sm:pl-8">
            <div className="h-full flex flex-col space-y-12">
              <div className="flex flex-col space-y-4">
                <p className="text-3xl" style={{ fontFamily: `${selectedHeading.name}` }}>Just another boring heading</p>
                <p className="text-lg text-gray-600" style={{ fontFamily: `${selectedBody.name}` }}>Just another boring bit of hero-section body copy. Nothing much to see here except for testing different fonts out. Hope this helps!</p>
              </div>
              <div className="flex flex-col sm:flex-row">
                <div className="w-auto h-auto">
                  <a
                    className="w-full sm:w-auto inline-flex justify-center px-8 py-4 bg-[#40916C] hover:bg-[#43AA8B] text-white font-medium text-md rounded-full"
                    style={{ fontFamily: `${selectedBody.name}` }}
                    href="#"
                  >
                    Test primary button
                  </a>
                </div>
                <div className="w-auto h-auto">
                  <a
                    className="w-full sm:w-auto inline-flex justify-center px-8 py-4 bg-white text-[#40916C] hover:text-[#43AA8B] font-medium text-md rounded-full"
                    style={{ fontFamily: `${selectedBody.name}` }}
                    href="#"
                  >
                    Test secondary button
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}